//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Main : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 SmoothLocomotion
        {
            get
            {
                return SteamVR_Actions.main_SmoothLocomotion;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.main_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.main_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean DialogInteract
        {
            get
            {
                return SteamVR_Actions.main_DialogInteract;
            }
        }
        
        public virtual SteamVR_Action_Boolean SkipSentence
        {
            get
            {
                return SteamVR_Actions.main_SkipSentence;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.main_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.main_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.main_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.main_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean ChannelSpell
        {
            get
            {
                return SteamVR_Actions.main_ChannelSpell;
            }
        }
    }
}
